=== 314537485/truelicense/truelicense-maven-archetype/src/test/filtered/projects/archetype.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
~ Copyright (C) 2005-2015 Schlichtherle IT Services.
~ All rights reserved. Use is subject to license terms.
-->
<schema elementFormDefault="qualified"
        targetNamespace="http://truelicense.org/xmlns/properties/archetype"
        xml:lang="en"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:a="http://truelicense.org/xmlns/properties/archetype">
    <element type="a:Archetype" name="archetype"/>
    <simpleType name="JavaIdentifier">
        <restriction>
            <simpleType>
                <restriction base="token">
                    <!-- Not exactly, but good enough for this purpose. -->
                    <pattern value="[A-Za-z_$][A-Za-z0-9_$]*"/>
                </restriction>
            </simpleType>
        </restriction>
    </simpleType>
    <simpleType name="JavaIdentifiers">
        <list itemType="a:JavaIdentifier"/>
    </simpleType>
    <simpleType name="KeyPairAlgorithm">
        <restriction base="token">
            <enumeration value="EC"/>
            <enumeration value="DSA"/>
            <enumeration value="RSA"/>
        </restriction>
    </simpleType>
    <simpleType name="KeyPairSize">
        <restriction base="positiveInteger">
            <minInclusive value="512"/>
        </restriction>
    </simpleType>
    <simpleType name="KeyStoreType">
        <restriction base="token">
            <enumeration value="JCEKS"/>
            <enumeration value="JKS"/>
            <enumeration value="PKCS12"/>
        </restriction>
    </simpleType>
    <simpleType name="LicenseKeyFormat">
        <restriction base="token">
            <enumeration value="V1"/>
            <enumeration value="V2/JSON"/>
            <enumeration value="V2/XML"/>
        </restriction>
    </simpleType>
    <complexType name="Archetype">
        <all>
            <element type="token" name="artifactId"/>
            <element type="token" name="artifactName" minOccurs="0"/>
            <element type="token" name="companyName"/>
            <element type="a:Password" name="defaultPassword"/>
            <element type="boolean" name="disableLicenseWizard" default="false" minOccurs="0"/>
            <element type="boolean" name="dynamicClassLoading" default="false" minOccurs="0"/>
            <element type="a:JavaIdentifiers" name="editions" minOccurs="0"/>
            <element type="nonNegativeInteger" name="freeTrialPeriod" default="0" minOccurs="0"/>
            <element type="token" name="ftpKeyStoreFile" minOccurs="0"/>
            <element type="token" name="ftpSecretMarkerClass" minOccurs="0"/>
            <element type="token" name="groupId"/>
            <element type="boolean" name="hideUninstallAction" minOccurs="0"/>
            <element type="token" name="keyGenLicenseValidationClass" minOccurs="0"/>
            <element type="a:ValidationFunction" name="keyGenLicenseValidationFunction" minOccurs="0"/>
            <element type="token" name="keyMgrClockClass" minOccurs="0"/>
            <element type="token" name="keyMgrLicenseValidationClass" minOccurs="0"/>
            <element type="a:ValidationFunction" name="keyMgrLicenseValidationFunction" minOccurs="0"/>
            <element type="a:KeyPairAlgorithm" name="keyPairAlgorithm" minOccurs="0"/>
            <element type="a:KeyPairSize" name="keyPairSize" minOccurs="0"/>
            <element type="a:KeyStoreType" name="keyStoreType" minOccurs="0"/>
            <element type="a:LicenseKeyFormat" name="licenseKeyFormat" default="V2/JSON" minOccurs="0"/>
            <element type="token" name="licensingSubject"/>
            <element type="token" name="package" minOccurs="0"/>
            <element type="a:PbeAlgorithm" name="pbeAlgorithm" minOccurs="0"/>
            <element type="a:PreferencesType" name="preferencesType" minOccurs="0"/>
            <element type="token" name="privateKeyStoreFile" minOccurs="0"/>
            <element type="token" name="publicKeyStoreFile" minOccurs="0"/>
            <element type="a:SignatureAlgorithm" name="signatureAlgorithm" minOccurs="0"/>
            <element type="token" name="trueLicenseVersion" minOccurs="0"/>
            <element type="boolean" name="verboseCli" minOccurs="0"/>
            <element type="token" name="version"/>
        </all>
    </complexType>
    <simpleType name="Password">
        <restriction base="string">
            <minLength value="8"/>
        </restriction>
    </simpleType>
    <simpleType name="PbeAlgorithm">
        <restriction base="token">
            <enumeration value="PBEWithMD5AndDES"/>
            <enumeration value="PBEWithSHA1AndDESede"/>
            <enumeration value="PBEWithHmacSHA1AndAES_128"/>
            <enumeration value="PBEWithHmacSHA224AndAES_128"/>
            <enumeration value="PBEWithHmacSHA256AndAES_128"/>
            <enumeration value="PBEWithHmacSHA384AndAES_128"/>
            <enumeration value="PBEWithHmacSHA512AndAES_128"/>
            <enumeration value="PBEWithHmacSHA1AndAES_256"/>
            <enumeration value="PBEWithHmacSHA224AndAES_256"/>
            <enumeration value="PBEWithHmacSHA256AndAES_256"/>
            <enumeration value="PBEWithHmacSHA384AndAES_256"/>
            <enumeration value="PBEWithHmacSHA512AndAES_256"/>
        </restriction>
    </simpleType>
    <simpleType name="PreferencesType">
        <restriction base="token">
            <enumeration value="system"/>
            <enumeration value="user"/>
        </restriction>
    </simpleType>
    <simpleType name="SignatureAlgorithm">
        <restriction base="token">
            <enumeration value="NONEwithDSA"/>
            <enumeration value="SHA1withDSA"/>
            <enumeration value="SHA224withDSA"/>
            <enumeration value="SHA256withDSA"/>
            <enumeration value="NONEwithECDSA"/>
            <enumeration value="SHA1withECDSA"/>
            <enumeration value="SHA224withECDSA"/>
            <enumeration value="SHA256withECDSA"/>
            <enumeration value="SHA384withECDSA"/>
            <enumeration value="SHA512withECDSA"/>
            <enumeration value="NONEwithRSA"/>
            <enumeration value="SHA1withRSA"/>
            <enumeration value="SHA224withRSA"/>
            <enumeration value="SHA256withRSA"/>
            <enumeration value="SHA384withRSA"/>
            <enumeration value="SHA512withRSA"/>
        </restriction>
    </simpleType>
    <simpleType name="ValidationFunction">
        <restriction base="token">
            <enumeration value="decorate"/>
            <enumeration value="override"/>
        </restriction>
    </simpleType>
</schema>

=== 314537485/truelicense/truelicense-maven-archetype/src/test/filtered/projects/disableLicenseWizard/archetype.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2005-2015 Schlichtherle IT Services.
  ~ All rights reserved. Use is subject to license terms.
  -->
<archetype xmlns="http://truelicense.org/xmlns/properties/archetype"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://truelicense.org/xmlns/properties/archetype ../archetype.xsd">
    <artifactId>disableLicenseWizard</artifactId>
    <companyName>Company Inc.</companyName>
    <defaultPassword>test1234</defaultPassword>
    <disableLicenseWizard>true</disableLicenseWizard>
    <groupId>com.company.product</groupId>
    <licensingSubject>Product 1</licensingSubject>
    <version>1.0-SNAPSHOT</version>
</archetype>

=== 314537485/truelicense/truelicense-maven-archetype/src/test/filtered/projects/v2JsonLicenseKeyFormat/archetype.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2005-2015 Schlichtherle IT Services.
  ~ All rights reserved. Use is subject to license terms.
  -->
<archetype xmlns="http://truelicense.org/xmlns/properties/archetype"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://truelicense.org/xmlns/properties/archetype ../archetype.xsd">
    <artifactId>v2JsonLicenseKeyFormat</artifactId>
    <companyName>Company Inc.</companyName>
    <defaultPassword>test1234</defaultPassword>
    <groupId>com.company.product</groupId>
    <licenseKeyFormat>V2/JSON</licenseKeyFormat>
    <licensingSubject>Product 1</licensingSubject>
    <version>1.0-SNAPSHOT</version>
</archetype>
